###
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "Jesus Sebastian",
    "edad": 23,
    "correo": "asdnasudn@sdsd.com"
}










###
GET  http://localhost:3000/api/usuarios HTTP/1.1








































###
GET  http://localhost:3000/api/usuarios/6286beb1312250319d8641ac HTTP/1.1

###
PUT http://localhost:3000/api/usuarios/6286beee312250319d8641ae HTTP/1.1
Content-Type: application/json

{
    "nombre": "Antonio Lopez",
    "edad": 50,
    "correo": "xdt@gmail.com"
}

###
DELETE http://localhost:3000/api/usuarios/6286d3ad5d952e3db4f5c62d HTTP/1.1